D3E1/D3E1/Models/DbConfig.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace D3E1.Models
{
    public class DbConfig
    {
        public string connectionString { get; set; }
    }
}

D3E1/D3E1/Models/Entities/Todo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace D3E1.Models.Entities
{
    public class Todo
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(25)]
        [Required]
        public string Title { get; set; }
        [MinLength(1)]
        [Required]
        public string Description { get; set; }
        [Required]
        public DateTime CreatedAt { get; set; }
        public DateTime? CompletedAt { get; set; }
        public bool IsCompleted { get; set; }
    }
}

D3E1/D3E1/Models/TodoContext.cs
using D3E1.Models.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace D3E1.Models
{
    public class TodoContext : DbContext
    {
        public TodoContext(DbContextOptions<TodoContext> options) : base(options)
        {

        }

        public DbSet<Todo> Todos { get; set; }
    }
}

D3E1/D3E1/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace D3E1.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

D3E1/D3E1/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using D3E1.Models;
using D3E1.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace D3E1.Pages
{
    public class IndexModel : PageModel
    {
        private TodoContext _context { get; set; }
        private List<Todo> todos;
        public List<Todo> Todos
        {
            get
            {
                if (todos == null)
                {
                    todos = new List<Todo>();
                    todos.AddRange(_context.Todos.ToList());
                }
                return todos;
            }
        }

        public IndexModel(TodoContext context)
        {
            _context = context;
        }

        public void OnGet()
        {

        }

        public IActionResult OnGetDelete(int id)
        {
            var todo = _context.Todos.Where(x => x.Id == id).FirstOrDefault();
            if(todo != null)
            {
                _context.Todos.Remove(todo);
                _context.SaveChanges();
            }
            return Page();
        }

        public IActionResult OnGetComplete(int id)
        {
            var todo = _context.Todos.Where(x => x.Id == id).FirstOrDefault();
            if (todo != null)
            {
                todo.IsCompleted = true;
                todo.CompletedAt = DateTime.Today;
                _context.SaveChanges();
            }
            return Page();
        }
    }
}

D3E1/D3E1/Pages/Todo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using D3E1.Models;
using D3E1.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace D3E1.Pages
{
    public class AddTodoModel : PageModel
    {
        private TodoContext _context { get; set; }
        [BindProperty]
        public Todo Todo { get; set; }

        public AddTodoModel(TodoContext context)
        {
            _context = context;
        }

        public void OnGet()
        {
            Todo = new Todo();
        }

        public void OnGetEdit(int id)
        {
            Todo = _context.Todos.Where(x => x.Id == id).FirstOrDefault();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if (Todo.Id != 0)
            {
                var todo = _context.Todos.Where(x => x.Id == Todo.Id).FirstOrDefault();
                todo.Title = Todo.Title;
                todo.Description = Todo.Description;
                todo.IsCompleted = false;
                todo.CompletedAt = null;
                _context.SaveChanges();
            }
            else
            {
                Todo.CreatedAt = DateTime.Today;
                _context.Todos.Add(Todo);
                _context.SaveChanges();
            }
            return RedirectToPage("index");
        }
    }
}

D3E1/D3E1/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<div class="container" style="padding-top:15px;">

    <div class="container">
        @foreach (var item in Model.Todos)
        {
            <div class="col-md-4">
                <div class="panel @((item.IsCompleted) ? "panel-success":"panel-default")">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-8">
                                <span>@item.Title</span>
                            </div>
                            <div class="col-xs-1">
                                @if (!item.IsCompleted)
                                {
                                    <a asp-page="Index" asp-page-handler="Complete" asp-route-id="@item.Id"><i class="glyphicon glyphicon-ok"></i></a>
                                }
                            </div>
                            <div class="col-xs-1">
                                <a asp-page="Todo" asp-page-handler="Edit" asp-route-id="@item.Id"><i class="glyphicon glyphicon-edit"></i></a>
                            </div>
                            <div class="col-xs-1">
                                <a asp-page="Index" asp-page-handler="Delete" asp-route-id="@item.Id"><i class="glyphicon glyphicon-trash"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        @item.Description
                    </div>
                    <div class="panel-footer">
                        <label>Created: @item.CreatedAt.ToString("dd-MMM-yy hh:mm:ss tt")</label>
                        @if (item.CompletedAt.HasValue && item.IsCompleted)
                        {
                            <label>Completed: @item.CompletedAt.Value.ToString("dd-MMM-yy hh:mm:ss tt")</label>
                        }
                    </div>
                </div>
            </div>
        }
                            </div>

                            <div class="pull-right">
                                <a asp-page="Todo" class="mdc-fab material-icons">
                                    <i class="glyphicon glyphicon-plus "></i>
                                </a>
                            </div>
                        </div>

D3E1/D3E1/Pages/Todo.cshtml
@page
@model D3E1.Pages.AddTodoModel
@{
    ViewData["Title"] = "Todo";
}

<h2>Todo</h2>

<form method="post">
    <input hidden asp-for="Todo.Id" />
    <div class="form-group">
        <label asp-for="Todo.Title"></label>
        <input asp-for="Todo.Title" class="form-control" />
        <span asp-validation-for="Todo.Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Todo.Description"></label>
        <input asp-for="Todo.Description" class="form-control" />
        <span asp-validation-for="Todo.Description" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

D3E1/D3E1/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - D3E1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/node_modules/material-components-web/dist/material-components-web.css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">D3E1</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content" >
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - D3E1</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/node_modules/material-components-web/dist/material-components-web.js"></script>
        <script>mdc.autoInit()</script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>